"""add user role

Revision ID: e895720e5ba4
Revises: 2a94fffe014f
Create Date: 2022-12-14 17:50:25.138659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e895720e5ba4"
down_revision = "2a94fffe014f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_role = postgresql.ENUM("super_admin", "admin", "user", name="user_role")
    user_role.create(op.get_bind())
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("super_admin", "admin", "user", name="user_role"),
            server_default="user",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
